import type { LabCard, LabDeck } from "./types";

function missionCard(
  id: string,
  name: string,
  frontText: string,
  backTitle: string,
  backText: string,
  tags: string[],
  effects: LabCard["effects"],
): LabCard {
  return {
    id,
    name,
    type: "Mission",
    cardKind: "mission",
    frontTitle: name,
    frontText,
    backTitle,
    backText,
    imageTone: "green",
    face: "front",
    faceUp: true,
    rotation: 0,
    tags: ["mission", ...tags],
    effects,
  };
}

function itemCard(
  id: string,
  name: string,
  type: string,
  frontText: string,
  backText: string,
  imageTone: LabCard["imageTone"],
  tags: string[],
  effects: LabCard["effects"],
): LabCard {
  return {
    id,
    name,
    type,
    cardKind: "item",
    frontTitle: name,
    frontText,
    backTitle: "Item Back",
    backText,
    imageTone,
    face: "front",
    faceUp: true,
    rotation: 0,
    tags: ["item", ...tags],
    effects,
  };
}

function characterCard(
  id: string,
  name: string,
  frontText: string,
  backText: string,
  imageTone: LabCard["imageTone"],
  tags: string[],
): LabCard {
  return {
    id,
    name,
    type: "Character",
    cardKind: "character",
    frontTitle: name,
    frontText,
    backTitle: "Source Soul",
    backText,
    imageTone,
    face: "front",
    faceUp: true,
    rotation: 0,
    tags: ["character", "source", ...tags],
    effects: [
      {
        id: `${id}-character-info`,
        label: "Playable Form",
        mode: "info",
        timing: "setup",
        action: "modifyStat",
        description: "Character Cards define the player's table stats, elements, and tuning identity.",
      },
    ],
  };
}

export const initialCards: Record<string, LabCard> = {
  "glass-orchard": missionCard(
    "glass-orchard",
    "Glass Orchard",
    "Wood world. Range 14-20. Check Body + Focus + Bond. Pressure Count 5. Loadout 3.",
    "Signal Static",
    "Pressure Stat: Focus. Block 1 Drain or lose 1 Focus.",
    ["world", "wood", "range", "focus"],
    [
      {
        id: "glass-orchard-target-range",
        label: "Check Range",
        mode: "info",
        timing: "final check",
        action: "compareTarget",
        operation: "compare",
        description: "Final total must land inside 14-20.",
      },
      {
        id: "glass-orchard-pressure",
        label: "Signal Static",
        mode: "must",
        timing: "pressure reveal",
        action: "modifyStat",
        operation: "subtract",
        stat: "Focus",
        value: 1,
        description: "If not blocked, lose 1 Focus.",
      },
    ],
  ),
  "ember-court": missionCard(
    "ember-court",
    "Ember Court",
    "Fire world. Surpass 18. Check Body + Charge. Pressure Count 4. Loadout 2.",
    "Trial By Spark",
    "Combat pressure. Must add +1 Body, then compare against Surpass.",
    ["world", "fire", "surpass", "combat"],
    [
      {
        id: "ember-court-target",
        label: "Surpass Gate",
        mode: "info",
        timing: "final check",
        action: "compareTarget",
        operation: "compare",
        description: "Final total must be 18 or higher.",
      },
      {
        id: "ember-court-pressure",
        label: "Trial By Spark",
        mode: "must",
        timing: "combat pressure",
        action: "modifyStat",
        operation: "add",
        stat: "Body",
        value: 1,
        description: "Forced heat adds +1 Body before the final check.",
      },
    ],
  ),
  "salt-mirror": missionCard(
    "salt-mirror",
    "Salt Mirror",
    "Water world. Precise 16. Check Focus + Resolve. Pressure Count 4. Loadout 3.",
    "Reflection Debt",
    "May lose 1 Bond to tune Focus by +1 or -1.",
    ["world", "water", "precise", "focus", "resolve"],
    [
      {
        id: "salt-mirror-target",
        label: "Precise Gate",
        mode: "info",
        timing: "final check",
        action: "compareTarget",
        operation: "compare",
        description: "Final total must equal 16 exactly.",
      },
      {
        id: "salt-mirror-tune",
        label: "Reflection Debt",
        mode: "may",
        timing: "pressure reveal",
        action: "modifyStat",
        operation: "choose",
        stat: "Focus",
        value: 1,
        description: "Lose 1 Bond to choose +1 Focus or -1 Focus.",
      },
    ],
  ),
  "iron-choir": missionCard(
    "iron-choir",
    "Iron Choir",
    "Metal world. Range 15-21. Check Resolve + Charge. Pressure Count 5. Loadout 3.",
    "Weight Of Proof",
    "Must subtract 1 Resolve unless an Armor or Relic is active.",
    ["world", "metal", "range", "resolve", "charge"],
    [
      {
        id: "iron-choir-target",
        label: "Check Range",
        mode: "info",
        timing: "final check",
        action: "compareTarget",
        operation: "compare",
        description: "Final total must land inside 15-21.",
      },
      {
        id: "iron-choir-pressure",
        label: "Weight Of Proof",
        mode: "must",
        timing: "pressure reveal",
        action: "modifyStat",
        operation: "subtract",
        stat: "Resolve",
        value: 1,
        description: "Lose 1 Resolve unless an Armor or Relic is active.",
      },
    ],
  ),
  "root-archive": missionCard(
    "root-archive",
    "Root Archive",
    "Earth world. Range 13-18. Check Bond + Guile. Pressure Count 3. Loadout 2.",
    "Old Promise",
    "May add +1 Bond. If this overshoots, discard one Item.",
    ["world", "earth", "range", "bond", "guile"],
    [
      {
        id: "root-archive-target",
        label: "Check Range",
        mode: "info",
        timing: "final check",
        action: "compareTarget",
        operation: "compare",
        description: "Final total must land inside 13-18.",
      },
      {
        id: "root-archive-bond",
        label: "Old Promise",
        mode: "may",
        timing: "pressure reveal",
        action: "modifyStat",
        operation: "add",
        stat: "Bond",
        value: 1,
        description: "Add +1 Bond, but an overshoot discards one Item.",
      },
    ],
  ),
  "sky-market": missionCard(
    "sky-market",
    "Sky Market",
    "Air world. Surpass 17. Check Guile + Focus. Pressure Count 4. Loadout 4.",
    "False Bargain",
    "Must choose: lose 1 Guile or shuffle one active Item back into the Item Deck.",
    ["world", "air", "surpass", "guile", "focus"],
    [
      {
        id: "sky-market-target",
        label: "Surpass Gate",
        mode: "info",
        timing: "final check",
        action: "compareTarget",
        operation: "compare",
        description: "Final total must be 17 or higher.",
      },
      {
        id: "sky-market-pressure",
        label: "False Bargain",
        mode: "must",
        timing: "pressure reveal",
        action: "modifyStat",
        operation: "subtract",
        stat: "Guile",
        value: 1,
        description: "Choose a penalty: lose 1 Guile or return one active Item.",
      },
    ],
  ),
  "ash-compass": itemCard(
    "ash-compass",
    "Ash Compass",
    "Tool",
    "May tune Focus by +1 or -1 during a Mission check.",
    "Tool / Fire / Focus",
    "gold",
    ["tool", "fire", "focus"],
    [
      {
        id: "focus-tune",
        label: "Tune Focus",
        mode: "may",
        timing: "mission check",
        action: "modifyStat",
        operation: "choose",
        stat: "Focus",
        value: 1,
        description: "Choose +1 Focus, -1 Focus, or skip.",
      },
    ],
  ),
  "iron-vow": itemCard(
    "iron-vow",
    "Iron Vow",
    "Relic",
    "Must add +2 Fortitude when a combat pressure is active.",
    "Relic / Metal / Fortitude",
    "cyan",
    ["relic", "metal", "fortitude", "combat"],
    [
      {
        id: "fortitude-add",
        label: "Metal Brace",
        mode: "must",
        timing: "combat pressure",
        action: "modifyStat",
        operation: "add",
        stat: "Fortitude",
        value: 2,
        description: "Automatically add +2 Fortitude.",
      },
    ],
  ),
  "root-key": itemCard(
    "root-key",
    "Root Key",
    "Bridge",
    "May enter Wood if harmonious. Then shuffle the Item Deck.",
    "Bridge / Wood / Kinship",
    "green",
    ["bridge", "wood", "kinship"],
    [
      {
        id: "wood-bridge",
        label: "Bridge Access",
        mode: "may",
        timing: "mission entry",
        action: "modifyStat",
        operation: "add",
        stat: "Access",
        value: 1,
        description: "Use as a Wood bridge for this attempt.",
      },
      {
        id: "shuffle-items",
        label: "Root Reorder",
        mode: "may",
        timing: "after play",
        action: "shuffleDeck",
        targetDeckId: "item-deck",
        description: "Shuffle the Item Deck after this card is used.",
      },
    ],
  ),
  "ember-blade": itemCard(
    "ember-blade",
    "Ember Blade",
    "Weapon",
    "May add +2 Body. If the Mission target is Precise, this becomes Must.",
    "Weapon / Fire / Body",
    "red",
    ["weapon", "fire", "body"],
    [
      {
        id: "ember-blade-body",
        label: "Burning Edge",
        mode: "may",
        timing: "mission check",
        action: "modifyStat",
        operation: "add",
        stat: "Body",
        value: 2,
        description: "Add +2 Body. Treat as risky in Precise Missions.",
      },
    ],
  ),
  "quiet-aegis": itemCard(
    "quiet-aegis",
    "Quiet Aegis",
    "Armor",
    "May block 1 pressure loss to Resolve or Body.",
    "Armor / Earth / Resolve",
    "cyan",
    ["armor", "earth", "resolve", "body"],
    [
      {
        id: "quiet-aegis-block",
        label: "Hold Shape",
        mode: "may",
        timing: "pressure reveal",
        action: "modifyStat",
        operation: "add",
        stat: "Block",
        value: 1,
        description: "Block 1 pressure loss to Resolve or Body.",
      },
    ],
  ),
  "tide-lantern": itemCard(
    "tide-lantern",
    "Tide Lantern",
    "Tool",
    "May tune Resolve by +1 or -1 in Water or Earth worlds.",
    "Tool / Water / Resolve",
    "cyan",
    ["tool", "water", "resolve"],
    [
      {
        id: "tide-lantern-resolve",
        label: "Soft Light",
        mode: "may",
        timing: "mission check",
        action: "modifyStat",
        operation: "choose",
        stat: "Resolve",
        value: 1,
        description: "Choose +1 Resolve, -1 Resolve, or skip.",
      },
    ],
  ),
  "mirror-seed": itemCard(
    "mirror-seed",
    "Mirror Seed",
    "Charm",
    "May copy one +1 or -1 tuning choice already used this Mission.",
    "Charm / Water / Echo",
    "green",
    ["charm", "water", "echo"],
    [
      {
        id: "mirror-seed-copy",
        label: "Echo Tuning",
        mode: "may",
        timing: "after tune",
        action: "modifyStat",
        operation: "choose",
        stat: "Any tuned stat",
        value: 1,
        description: "Copy one small tuning choice already used this Mission.",
      },
    ],
  ),
  "signal-net": itemCard(
    "signal-net",
    "Signal Net",
    "Instrument",
    "May draw 1 Item after surviving a Focus pressure.",
    "Instrument / Air / Focus",
    "gold",
    ["instrument", "air", "focus", "draw"],
    [
      {
        id: "signal-net-draw",
        label: "Catch Signal",
        mode: "may",
        timing: "after focus pressure",
        action: "drawCard",
        targetDeckId: "item-deck",
        description: "Draw 1 Item after surviving a Focus pressure.",
      },
    ],
  ),
  "stone-ration": itemCard(
    "stone-ration",
    "Stone Ration",
    "Consumable",
    "May add +1 Resolve, then discard this Item.",
    "Consumable / Earth / Resolve",
    "gold",
    ["consumable", "earth", "resolve"],
    [
      {
        id: "stone-ration-resolve",
        label: "Steady Bite",
        mode: "may",
        timing: "pressure reveal",
        action: "modifyStat",
        operation: "add",
        stat: "Resolve",
        value: 1,
        description: "Add +1 Resolve, then discard this Item.",
      },
    ],
  ),
  "hollow-map": itemCard(
    "hollow-map",
    "Hollow Map",
    "Tool",
    "May peek at the next Mission. Then shuffle the Mission Deck.",
    "Tool / Air / Mission",
    "cyan",
    ["tool", "air", "mission", "shuffle"],
    [
      {
        id: "hollow-map-info",
        label: "Scout World",
        mode: "may",
        timing: "before mission draw",
        action: "shuffleDeck",
        targetDeckId: "mission-deck",
        description: "Peek at the next Mission, then shuffle the Mission Deck.",
      },
    ],
  ),
  "alloy-latch": itemCard(
    "alloy-latch",
    "Alloy Latch",
    "Key",
    "May bridge Metal or Wood for one Mission entry.",
    "Key / Metal + Wood / Access",
    "cyan",
    ["key", "bridge", "metal", "wood", "access"],
    [
      {
        id: "alloy-latch-access",
        label: "Cross-Hinge",
        mode: "may",
        timing: "mission entry",
        action: "modifyStat",
        operation: "add",
        stat: "Access",
        value: 1,
        description: "Bridge Metal or Wood for one Mission entry.",
      },
    ],
  ),
  "memory-thread": itemCard(
    "memory-thread",
    "Memory Thread",
    "Anchor",
    "May keep one discovered pressure note after a failed Mission.",
    "Anchor / Water / Memory",
    "green",
    ["anchor", "water", "memory"],
    [
      {
        id: "memory-thread-note",
        label: "Keep A Thread",
        mode: "may",
        timing: "failed mission",
        action: "modifyStat",
        description: "Keep one discovered pressure note after a failed Mission.",
      },
    ],
  ),
  sweetpea: characterCard(
    "sweetpea",
    "Sweetpea",
    "Earth + Earth range-tuning scout. Body 5, Resolve 4, Focus 6 +/-1, Guile 3, Bond 6 +/-1, Charge 4.",
    "Western: Capricorn. Chinese: Earth Goat. Source stats: Presence 47, Wealth 75, Fortitude 103, Cunning 72, Flair 46, Vigor 40, Kinship 97, Potency 62, Wisdom 78, Prestige 77, Influence 69, Arcana 91.",
    "cyan",
    ["earth", "earth", "range-tuning", "sweetpea"],
  ),
  "kael-ember": characterCard(
    "kael-ember",
    "Kael Ember",
    "Fire + Metal pressure breaker. Body 7, Resolve 5, Focus 3, Guile 4, Bond 3, Charge 8 +/-2.",
    "Mock source profile for simulation. Strong at Surpass and combat pressure, weaker at Bond and Focus.",
    "red",
    ["fire", "metal", "combat", "surpass"],
  ),
  "mira-tide": characterCard(
    "mira-tide",
    "Mira Tide",
    "Water + Air precision navigator. Body 3, Resolve 6, Focus 8 +/-2, Guile 7 +/-1, Bond 4, Charge 3.",
    "Mock source profile for simulation. Strong at Precise and hidden information, weaker at Body and Charge.",
    "green",
    ["water", "air", "precise", "scout"],
  ),
};

export const initialDecks: Record<string, LabDeck> = {
  "mission-deck": {
    id: "mission-deck",
    name: "Mission Deck",
    maxCards: null,
    cardIds: [
      "glass-orchard",
      "ember-court",
      "salt-mirror",
      "iron-choir",
      "root-archive",
      "sky-market",
    ],
  },
  "item-deck": {
    id: "item-deck",
    name: "Item Deck",
    maxCards: null,
    cardIds: [
      "ash-compass",
      "iron-vow",
      "root-key",
      "ember-blade",
      "quiet-aegis",
      "tide-lantern",
      "mirror-seed",
      "signal-net",
      "stone-ration",
      "hollow-map",
      "alloy-latch",
      "memory-thread",
    ],
  },
};
